Update host and database config keys
Without this change, I get an error like this:

```
Error: execution error at (aidbox/templates/configmap.yaml:14:22): missing config BOX_DB_DATABASE value
helm.go:86: 2025-08-11 15:06:32.836226 +1000 AEST m=+0.291273543 [debug] execution error at (aidbox/templates/configmap.yaml:14:22): missing config BOX_DB_DATABASE value
```